### ISSUE TITLE
Add the Pod

### ISSUE THREAD

**Issue by grace-omotoso** [MLH-Fellowship/pod-4.1.3-portfolio#1]
Currently, then repository has members of the MLH team on it, but you should replace them with members of the pod.

You can update information in `_data/fellows.yml`

You should work on:
- [ ] Replacing the images
- [ ] Update the names and locations of each fellow
- [ ] Update the pod number inside of `_config.yml`

**Comment by Young-Einstein10** [comment]
@grace-omotoso Please how do you suggest I get the images of each team member? 
I thought of getting them from their Github profile but a number of us didn't upload and profile picture or specify our location.

**Comment by Young-Einstein10** [comment]
@grace-omotoso I'm done adding the images and updating the location, but the images are not responsive, so we're thinking of using a carousel for this. Can we go on with the fix or another issue will be created for that?
![image](https://user-images.githubusercontent.com/45533201/141110574-c4135ba9-96f0-48ee-8cd5-029694eeeb9b.png)

**Comment by grace-omotoso** [comment]
Using a carousel will be better. Ideally, do not clog the navbar with the images. Let us have another section for that in the main page. Something like this
<img width="564" alt="meet_the_pod" src="https://user-images.githubusercontent.com/13639240/141189421-46de5aa4-2a88-48ba-b6d3-47e05233231a.PNG">

**Comment by Young-Einstein10** [comment]
Alright...we'll implement this.
Thanks for the sample
