### ISSUE TITLE
Improve Navbar

### ISSUE THREAD

**Issue by grace-omotoso** [MLH-Fellowship/pod-4.1.3-portfolio#21]
The Navbar has four images and a generic pod number. Do the following to improve its look:

- [ ] Shift MLH Prep to the left
- [ ] Replacing the images with a pod logo (Come up with a logo that depicts our pod name)
- [ ] Under the pod log, replace the generic pod number with our Pod name i.e Hacktivists
- [ ] Under the pod name, display our pod number - pod 4.1.3
- [ ] Feel free to change the nav bar color if necessary but must not be off when compared with the entire project

**Comment by akshitadixit** [comment]
@grace-omotoso the shifting the logo to the left has been already done
