### ISSUE TITLE
Add a navigation bar

### ISSUE THREAD

**Issue by grace-omotoso** [MLH-Fellowship/pod-4.1.3-portfolio#4]
As the portfolio gains more information, it may make sense to add a navigation bar. This bar should include the logo on the left side but only once the page has scrolled down a bit.

**Comment by akshitadixit** [comment]
@grace-omotoso please confirm the items we will need on the nav bar. Currently we have added the logo on the left and `Home`, `Meet the pod` and `Projects` on the right.

**Comment by grace-omotoso** [comment]
@akshitadixit we can have a Fellow Locator that takes the user to the map area. Though we don't have the map yet, you can just include it on the Navbar. The team working on the map can link the navbar to the map later on.
