### ISSUE TITLE
Add pod stats

### ISSUE THREAD

**Issue by akshitadixit** [MLH-Fellowship/pod-4.1.3-portfolio#42]
What better than the collective stats of the entire pod on the portfolio, hence we wish to add the following to the portfolio:

- [ ] An indicator that shows no. of days spent v/s no. of days left in the fellowship
- [ ] Next pod meeting date and time
- [ ] Total number of issues raised by the pod and Total no. of PR's merged by the pod
- [ ] No. of visits on the portfolio page

**Comment by sumana2001** [comment]
I don't think we should display the pod meeting and time in the portfolio as portfolios I feel are meant for showing who you are and what you have done, but the rest of the issue sounds cool. If @akshitadixit you're not working on it, I would like to give it a try, of course, if @grace-omotoso approves.

**Comment by akshitadixit** [comment]
Hi @sumana2001 agree with the suggestion, however I did want to work on the issue. You could be a helping hand if you wish, I will definitely need it :cry:

**Comment by grace-omotoso** [comment]
@akshitadixit This does not appear to be a major use case, we may have the issue closed.
