### ISSUE TITLE
Overlap of animation and photo in "Meet the Pod" section

### ISSUE THREAD

**Issue by iamwyh2019** [MLH-Fellowship/pod-4.1.3-portfolio#51]
In the "Meet the Pod" section, when the mouse hovers on one card, his/her name goes up too much that it overlaps with the photo.
![微信截图_20211113222254](https://user-images.githubusercontent.com/51950361/141647352-385392a2-83e2-43f5-975b-890b9699c41e.png)

And also, Priya's photo is rotated.

**Comment by iamwyh2019** [comment]
I will fix this

**Comment by PriyaBihani** [comment]
It's alright, I will fix this. Might be quicker. Also, where is photo rotated?

**Comment by iamwyh2019** [comment]
Oh, I already fixed it and is writing the pr. Thanks a lot!
