### ISSUE TITLE
Add social icons for fellows

### ISSUE THREAD

**Issue by grace-omotoso** [MLH-Fellowship/pod-4.1.3-portfolio#8]
At the moment, it only displays the fellow name and location. To help people network, we should add social icons to each of the fellow cards.

![Screenshot 2021-09-30 at 14 24 40](https://user-images.githubusercontent.com/34094921/135463524-d5ddd708-920c-4fc0-ba87-02ca80186d9e.png)
- [x] Add LinkedIn icons to the card
- [x] Add Twitter icons to the card
- [x] Add Resume icons to the card
- [x] Add GitHub icons to the card

**Comment by PriyaBihani** [comment]
@grace-omotoso I am working on the issue #3 (adding profile page for each fellow), I thought it also includes creating a card and adding social icons, So I added it there itself. I hope that it's okay with you.

**Comment by grace-omotoso** [comment]
okay, that is fine. I have assigned it to you.

**Comment by PriyaBihani** [comment]
Hey, @grace-omotoso  this issue is resolved in above merged PR. You can close this issue.
