### ISSUE TITLE
Add Dark Theme toggle

### ISSUE THREAD

**Issue by grace-omotoso** [MLH-Fellowship/pod-4.1.3-portfolio#9]
I want to add a toggle to swap the website to a dark theme. There could also be an option to match the system theme too

**Comment by grace-omotoso** [comment]
@sumana2001 @SciencePotato what is the update with the dark theme mode?

**Comment by SciencePotato** [comment]
Sorry, I wasn't able to do much, I had school from 10 to now, I'll start working on it ASAP. 
So far, I've only added the slider and the cookie.

**Comment by SciencePotato** [comment]
It's able to toggle between Dark Mode and Default, now the only thing left is selecting the element and styling it.

**Comment by SciencePotato** [comment]
![image](https://user-images.githubusercontent.com/64312205/141599964-7f6f00b0-668a-41ac-90af-74402615f93d.png)

![image](https://user-images.githubusercontent.com/64312205/141600004-86f01e98-8663-4b2b-9914-a59d8ff970e9.png)

![image](https://user-images.githubusercontent.com/64312205/141599978-ad756495-d492-48d8-ab93-27ebc0f973be.png)

![image](https://user-images.githubusercontent.com/64312205/141600020-d3c85b11-47e8-4a38-b491-2f086db5a072.png)

![image](https://user-images.githubusercontent.com/64312205/141599986-046cbb45-c7ff-40c9-ac48-35b84c561bf1.png)

![image](https://user-images.githubusercontent.com/64312205/141600026-7c4c9e57-f47c-44ac-b9c8-f6a0302c7e34.png)

Would this color scheme be sufficient?
